config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'

  get '/home', to: 'static_pages#home', as: 'home'

  get '/help', to: 'static_pages#help', as: 'help'

  get '/about', to: 'static_pages#about', as: 'about'

  get '/contact', to: 'static_pages#contact', as: 'contact'

  get '/signup', to: 'users#new', as: 'signup'

  resources :users do
    member do
      get :following, :followers
    end
  end
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get     '/login',     to: 'sessions#new'
  post    '/login',     to: 'sessions#create'
  delete  '/logout',    to: 'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build if logged_in?
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_welcome.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("https://www.nitrous.io/images/stacks/rails.png", alt: "Rails logo"),
    'http://rubyonrails.org/' %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
    The
    <a href="http://www.railstutorial.org/">
        <em>Ruby on Rails Tutorial</em>
    </a>
    is a
    <a href="http://www.railstutorial.org/book">book</a>
    and
    <a href="http://screencasts.railstutorial.org/">screencast series</a>
    to teach web development with
    <a href="http://rubyonrails.org/">Ruby on Rails</a>. This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide :title, "Contact" %>
<h1>Contact</h1>
<p>
  Here is my email address <address class="">sontd.it@gmail.com</address>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
    Get help on the Ruby on Rails Tutorial at the
    <a href="http://www.railstutorial.org/help">Rails Tutorial help page</a>. To get help on this sample app, see the
    <a href="http://www.railstutorial.org/book">
        <em>Ruby on Rails Tutorial</em>
        book</a>.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <%= render 'microposts/micropost_feed' %>
<% else %>
  <%= render 'welcome' %>
<% end %>